//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelDesktopApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelDesktopApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Sticker.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not ask me again.
        /// </summary>
        public static string CheckBoxContent {
            get {
                return ResourceManager.GetString("CheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts.
        /// </summary>
        public static string DefaultImageName1 {
            get {
                return ResourceManager.GetString("DefaultImageName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack man.
        /// </summary>
        public static string DefaultImageName2 {
            get {
                return ResourceManager.GetString("DefaultImageName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario.
        /// </summary>
        public static string DefaultImageName3 {
            get {
                return ResourceManager.GetString("DefaultImageName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minion.
        /// </summary>
        public static string DefaultImageName4 {
            get {
                return ResourceManager.GetString("DefaultImageName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alien.
        /// </summary>
        public static string DefaultImageName5 {
            get {
                return ResourceManager.GetString("DefaultImageName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom.
        /// </summary>
        public static string DefaultImageName6 {
            get {
                return ResourceManager.GetString("DefaultImageName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Giraffe.
        /// </summary>
        public static string DefaultImageName7 {
            get {
                return ResourceManager.GetString("DefaultImageName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Painting.
        /// </summary>
        public static string DefaultImageName8 {
            get {
                return ResourceManager.GetString("DefaultImageName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Giraffe and his friends.
        /// </summary>
        public static string DefaultImageName9 {
            get {
                return ResourceManager.GetString("DefaultImageName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ExitConfirmMsg {
            get {
                return ResourceManager.GetString("ExitConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Spread the Word.
        /// </summary>
        public static string MsgBoxCaption {
            get {
                return ResourceManager.GetString("MsgBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe Later.
        /// </summary>
        public static string MsgBoxLeftBtn {
            get {
                return ResourceManager.GetString("MsgBoxLeftBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this app, please rate it in the App Store. Thanks!.
        /// </summary>
        public static string MsgBoxMsg {
            get {
                return ResourceManager.GetString("MsgBoxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate It Now.
        /// </summary>
        public static string MsgBoxRightBtn {
            get {
                return ResourceManager.GetString("MsgBoxRightBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Pivot1Title {
            get {
                return ResourceManager.GetString("Pivot1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Pivot2Title {
            get {
                return ResourceManager.GetString("Pivot2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Pivot3Title {
            get {
                return ResourceManager.GetString("Pivot3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Successfully!.
        /// </summary>
        public static string UpdateSuccessfullyMsg {
            get {
                return ResourceManager.GetString("UpdateSuccessfullyMsg", resourceCulture);
            }
        }
    }
}
